config/routes.rb
Rails.application.routes.draw do
  resources :owners
  resources :vehicles
  resources :booking_details
  resources :users  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking_detail.rb
class BookingDetail < ApplicationRecord
end

app/models/owner.rb
class Owner < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/booking_details_controller.rb
class BookingDetailsController < ApplicationController
  before_action :set_booking_details, only: [:show, :edit, :update, :destroy]

  # GET /booking_details
  # GET /booking_details.json
  def index
    @booking_details = BookingDetail.all
  end

  # GET /booking_details/1
  # GET /booking_details/1.json
  def show
  end

  # GET /booking_details/new
  def new
    @booking_details = BookingDetail.new
  end

  # GET /booking_details/1/edit
  def edit
  end

  # POST /booking_details
  # POST /booking_details.json
  def create
    @booking_details = BookingDetail.new(booking_details_params)

    respond_to do |format|
      if @booking_details.save
        format.html { redirect_to @booking_details, notice: 'Booking Details was successfully created.' }
        format.json { render :show, status: :created, location: @booking_details }
      else
        format.html { render :new }
        format.json { render json: @booking_details.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booking_details/1
  # PATCH/PUT /booking_details/1.json
  def update
    respond_to do |format|
      if @booking_details.update(booking_details_params)
        format.html { redirect_to @booking_details, notice: 'Booking Details was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking_details }
      else
        format.html { render :edit }
        format.json { render json: @booking_details.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booking_details/1
  # DELETE /booking_details/1.json
  def destroy
    @booking_details.destroy
    respond_to do |format|
      format.html { redirect_to booking_details_url, notice: 'Booking Details was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking_details
      @booking_details = BookingDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_details_params
      params.require(:booking_detail).permit(:timestamps, :date_from, :date_to, :rent_per_day)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:owner_name, :address, :contact, :aadhar_no)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :address, :contact, :aadhar_no, :license)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:vehicle_type, :reg_no, :availability)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/booking_details/_form.html.erb
<%= form_with(model: booking_details, local: true) do |form| %>
  <% if booking_details.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking_details.errors.count, "error") %> prohibited this booking_detail from being saved:</h2>

      <ul>
      <% booking_details.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_from %>
    <%= form.date_field :date_from %>
  </div>

  <div class="field">
    <%= form.label :date_to %>
    <%= form.date_field :date_to %>
  </div>

  <div class="field">
    <%= form.label :rent_per_day %>
    <%= form.text_field :rent_per_day %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/booking_details/edit.html.erb
<h1>Editing Booking_Details</h1>

<%= render 'form', booking_details: @booking_details %>

<%= link_to 'Show', @booking_details %> |
<%= link_to 'Back', booking_details_path %>

app/views/booking_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Booking_Details</h1>

<table>
  <thead>
    <tr>
      <th>Date From</th>
      <th>Date To</th>
      <th>Rent Per Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @booking_details.each do |booking_details| %>
      <tr>
        <td><%= booking_details.date_from %></td>
        <td><%= booking_details.date_to %></td>
        <td><%= booking_details.rent_per_day %></td>
        <td><%= link_to 'Show', booking_details %></td>
        <td><%= link_to 'Edit', edit_booking_detail_path(booking_details) %></td>
        <td><%= link_to 'Destroy', booking_details, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_detail_path %>

app/views/booking_details/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking_details: @booking_details %>

<%= link_to 'Back', booking_details_path %>

app/views/booking_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date from:</strong>
  <%= @booking_details.date_from %>
</p>

<p>
  <strong>Date to:</strong>
  <%= @booking_details.date_to %>
</p>

<p>
  <strong>Rent per day:</strong>
  <%= @booking_details.rent_per_day %>
</p>

<%= link_to 'Edit', edit_booking_detail_path(@booking_details) %> |
<%= link_to 'Back', booking_details_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/owners/_form.html.erb
<%= form_with(model: owner, local: true) do |form| %>
  <% if owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :owner_name %>
    <%= form.text_field :owner_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact %>
  </div>

  <div class="field">
    <%= form.label :aadhar_no %>
    <%= form.text_field :aadhar_no %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Owners</h1>

<table>
  <thead>
    <tr>
      <th>Owner name</th>
      <th>Address</th>
      <th>Contact</th>
      <th>Aadhar no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.owner_name %></td>
        <td><%= owner.address %></td>
        <td><%= owner.contact %></td>
        <td><%= owner.aadhar_no %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner name:</strong>
  <%= @owner.owner_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @owner.address %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @owner.contact %>
</p>

<p>
  <strong>Aadhar no:</strong>
  <%= @owner.aadhar_no %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact %>
  </div>

  <div class="field">
    <%= form.label :aadhar_no %>
    <%= form.text_field :aadhar_no %>
  </div>

  <div class="field">
    <%= form.label :license %>
    <%= form.text_field :license %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>users</h1>

<table>
  <thead>
    <tr>
      <th>user name</th>
      <th>address</th>
      <th>contact</th>
      <th>aadhar_no</th>
      <th>license</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_name %></td>
        <td><%= user.address %></td>
        <td><%= user.contact %></td>
        <td><%= user.aadhar_no %></td>
        <td><%= user.license %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>user name:</strong>
  <%= @user.user_name %>
</p>

<p>
  <strong>address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>contact:</strong>
  <%= @user.contact %>
</p>

<p>
  <strong>aadhar_no:</strong>
  <%= @user.aadhar_no %>
</p>

<p>
  <strong>license:</strong>
  <%= @user.license %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vehicle_type %>
    <%= form.text_field :vehicle_type %>
  </div>

  <div class="field">
    <%= form.label :reg_no %>
    <%= form.text_field :reg_no %>
  </div>

  <div class="field">
    <%= form.label :availability %>
    <%= form.check_box :availability %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Vehicle type</th>
      <th>Reg no</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.vehicle_type %></td>
        <td><%= vehicle.reg_no %></td>
        <td><%= vehicle.availability %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vehicle type:</strong>
  <%= @vehicle.vehicle_type %>
</p>

<p>
  <strong>Reg no:</strong>
  <%= @vehicle.reg_no %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @vehicle.availability %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>